language: python

python:
  - 3.7

dist: xenial
sudo: true

stages:
  - test-links
  - build
  - name: deploy
    if: branch = master  # Deploy only on master commits

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: test-links
      script: pipenv run make linkcheck
    - stage: build
      script: pipenv run make html
    - stage: deploy
      script: pipenv run make html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: docs/html
        on:
          branch: master  # You can't be safe enough <insert double condom joke here>
